# Dev mode - uses Quarkus Dev Services to start PostgreSQL automatically
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus_test
quarkus.datasource.password=quarkus_test

# Test mode - disable dev services for tests
%test.quarkus.devservices.enabled=false
%test.quarkus.datasource.db-kind=postgresql
%test.quarkus.datasource.username=quarkus
%test.quarkus.datasource.password=quarkus
%test.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_test

# Production mode - uses external PostgreSQL
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:15432/quarkus_test
%prod.quarkus.datasource.jdbc.max-size=8
%prod.quarkus.datasource.jdbc.min-size=2

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.openapi.generator.spec=warehouse-openapi.yaml
quarkus.openapi.generator.base-package=com.warehouse.api